---
title: "Walrasian Labor Market"
output: 
  github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE }
library(dplyr)
library(ggplot2)
library(tidyr)
library(sandwich)
library(lmtest)
library(patchwork)
library(MASS)
library(brms)
```


Walrasian Equilibrium :  $L^s(w)=L^d(w)=L$

The market clears when the quantity of labor demanded $L$ by the firm exactly equals to the quantity of labor supplied by the workers at a specific market-clearing wage $w$ .

-   $L^s(w)$ :  Labor supply function (The workers)

-   $L^d(w)$ : Labor demand function (The Firms)

Where : 

$$
\frac{\partial L^s}{\partial w} > 0 , \frac{\partial L^d}{\partial w} < 0
$$

- When wage decreases, companies want to hire more (downward-sloping) -> $\frac{\partial L^d}{\partial w} < 0$

- When wage increases, workers want to work more (upward-sloping) -> $\frac{\partial L^s}{\partial w} > 0$

The firm sets the labor demand so that $w = MPL$ , where $MPL$ is the **Marginal Product of Labor (MPL)** — the additional output produced by one more unit of labor. When wage equals $MPL$, the firm has no incentive to hire more or less.

Wage can be expressed as follow : 

$$w=\frac{U'_{leisure}}{U'_{consumption}}$$ 

-   $U'_{leisure}$ : Marginal Utility of Leisure

-   $U'_{consumption}$ : Marginal Utility of Consumption

This ratio is called **Marginal Rate of Substitution (MRS)**.

The market requires both conditions simultaneously : 

$$
w= MPL = \frac{U'_{leisure}}{U'_{consumption}}
$$

The workers and the firm optimize the wage by setting $w$ as $w = MRS$ and $w = MPL$ respectively. The market clears when $MRS = MPL$

In a pure Walrasian World, the reserve army and the elite overproduction cannot mathematically exist, but in the actual economy, the markets do not clear instantly because of frictions — skill mismatch, position scarcity...

**Excess demand function** : The Walrasian tatonnement works through excess demand 

$$
ED(w) = L^d(w) - L^s(w)  
$$

- $ED>0$ : more demand than supply -> wage rises

- $ED<0$ : more supply than demand -> wage falls

- $ED = 0$ : market clears -> equilibrium

The frictions are the mechanisms that keep $ED \neq 0$ persistently.

#### Tier 1 : standard reserve army 

**Friction 1 : Automation**

Automation causes labor displacement that forces job-to-job transitions, and since the skills of the displaced workers are considered obsolete, it will result to a relatively prolonged unemployment to acquire new skills for the existing positions . Thus, automation prevents the equilibrium of the Walrasian model. 

Automation is a capital-substitute for labor : firms choose to demand less labor because the machines can do the job. So automation affects the labor demand. 

By introducing this friction to the $MPL$ , the wage will be expressed with a time varying technology parameter $A(t)$ .
$MPL$ is a derivative of the Production function (Cobb-Douglas) : 

$$
Y = A(t) \cdot K^{\alpha} \cdot L^{(1 - \alpha)}
$$

- $A$ : Time varying technology parameter

- $K$ : Capital

- $L$ : Labor

- $\alpha$ and $1 - \alpha$ : Distribution of the income between the capital and the Labor. Typically $\alpha = 0.3$ and $1-\alpha = 0.7$ 

For this project, the labor is splitted to automatable labor $L_a$ and non-automatable labor $L_n$. $L_a$ is composed by the workers who perform routine, codifiable tasks that machines can replace, while $L_n$ represents the workers who perform tasks that complement rather than compete automation — creativity, judgment, social interaction, complex problem solving. So the production function become : 

$$
Y = A(t) \cdot K^{\alpha} \cdot \tilde{L}^{(1 - \alpha)} 
$$

with $\tilde{L}$ = $L_n + \theta(t) \cdot L_a$ . $\theta(t)$ is an automation coefficient — how productive automatable workers are relative to machines.

To determine $MPL$ , we take the derivative of $Y$ with respect to $L_a$ . Using the chain rule : 

$$MPL = \frac{\partial Y}{\partial L_a} = \frac{\partial Y}{\partial \tilde{L} } \cdot \frac{\partial \tilde{L}}{\partial L_a }$$

$$\frac{\partial Y}{\partial \tilde{L} } = (1- \alpha) A(t) \cdot K^{\alpha} \cdot \tilde{L}^{- \alpha}$$

$$\frac{\partial {\tilde{L}}}{\partial L_a } = \theta (t)$$

$$MPL = w = (1- \alpha)\cdot \theta(t)\cdot \frac {A(t) \cdot K^{\alpha}}{(L_n + \theta(t) \cdot L_a)^{\alpha}}$$

Automation reduces the demand of automatable labor $L^d_a$ . To get $L^d_a$ , we solve the equation above for $L_a$ as a function of the wage $w$

**Friction 2 : Workers can not move to a new sector instantly**

#### Tier 2 : elite reserve army (elite overproduction)
